CREATE TABLE IF NOT EXISTS advisory_sessions (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id         INT UNSIGNED    NOT NULL,
    path_type       ENUM('A','B')   NOT NULL,
    business_idea   VARCHAR(255)    DEFAULT NULL,
    district        VARCHAR(100)    NOT NULL,
    ward            VARCHAR(100)    DEFAULT NULL,
    village         VARCHAR(100)    DEFAULT NULL,
    capital_tzs     DECIMAL(15,2)   DEFAULT NULL,
    age_at_query    TINYINT UNSIGNED DEFAULT NULL,
    gender          ENUM('male','female','other') DEFAULT NULL,
    isic_code       SMALLINT UNSIGNED DEFAULT NULL,
    result_json     JSON            NOT NULL,
    success_chance  ENUM('Low','Medium','High') DEFAULT NULL,
    monthly_profit  DECIMAL(15,2)   DEFAULT NULL,
    roi_percent     DECIMAL(8,2)    DEFAULT NULL,
    breakeven_months DECIMAL(6,1)   DEFAULT NULL,
    created_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_user_id    (user_id),
    INDEX idx_path_type  (path_type),
    INDEX idx_created_at (created_at),
    INDEX idx_success    (success_chance)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
